#!/usr/bin/env node
/**
 * HD Wallet Aligned Code Generator
 *
 * Generates C++, TypeScript, and JavaScript code from the aligned FlatBuffers schema.
 * Uses the flatc-wasm aligned codegen for zero-copy WASM interop.
 *
 * Usage:
 *   node scripts/generate-aligned.mjs
 *   node scripts/generate-aligned.mjs --schema schemas/hd_wallet_aligned.fbs
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Get script directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, '..');

// Try to import the aligned codegen from flatc-wasm
let generateAlignedCode;
try {
  // Try local flatbuffers first (for development)
  const localPath = '/Users/tj/software/flatbuffers/wasm/src/aligned-codegen.mjs';
  const codegen = await import(localPath);
  generateAlignedCode = codegen.generateAlignedCode;
  console.log('Using local flatbuffers aligned codegen');
} catch (e) {
  try {
    // Fall back to installed package
    const codegen = await import('flatc-wasm/aligned-codegen');
    generateAlignedCode = codegen.generateAlignedCode;
    console.log('Using flatc-wasm package');
  } catch (e2) {
    console.error('Error: Could not load aligned codegen');
    console.error('Install flatc-wasm or ensure local flatbuffers path is correct');
    process.exit(1);
  }
}

// Parse command line arguments
const args = process.argv.slice(2);
let schemaPath = join(projectRoot, 'schemas', 'hd_wallet_aligned.fbs');

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--schema' && args[i + 1]) {
    schemaPath = resolve(args[i + 1]);
    i++;
  }
}

// Paths
const outputDir = join(projectRoot, 'generated', 'aligned');
const cppOutputPath = join(outputDir, 'hd_wallet_aligned.h');
const tsOutputPath = join(outputDir, 'hd_wallet_aligned.ts');
const jsOutputPath = join(outputDir, 'hd_wallet_aligned.mjs');

// Ensure output directory exists
if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

// Read schema
console.log(`Reading schema: ${schemaPath}`);
let schemaContent;
try {
  schemaContent = readFileSync(schemaPath, 'utf-8');
} catch (e) {
  console.error(`Error reading schema file: ${schemaPath}`);
  console.error(e.message);
  process.exit(1);
}

// Generate code
console.log('Generating aligned code...');
const result = generateAlignedCode(schemaContent, {
  includeGuard: true,
  pragmaOnce: true,
  defaultStringLength: 0, // No string fields in this schema
});

// Write C++ header
console.log(`Writing C++ header: ${cppOutputPath}`);
const cppHeader = `/**
 * @file hd_wallet_aligned.h
 * @brief Auto-generated aligned structs for HD Wallet WASM
 *
 * DO NOT EDIT - Generated by scripts/generate-aligned.mjs
 * Source: schemas/hd_wallet_aligned.fbs
 */

${result.cpp}`;
writeFileSync(cppOutputPath, cppHeader);

// Write TypeScript
console.log(`Writing TypeScript: ${tsOutputPath}`);
const tsContent = `/**
 * Auto-generated aligned buffer accessors for HD Wallet WASM
 *
 * DO NOT EDIT - Generated by scripts/generate-aligned.mjs
 * Source: schemas/hd_wallet_aligned.fbs
 */

${result.ts}`;
writeFileSync(tsOutputPath, tsContent);

// Write JavaScript (ESM)
console.log(`Writing JavaScript: ${jsOutputPath}`);
const jsContent = `/**
 * Auto-generated aligned buffer accessors for HD Wallet WASM
 *
 * DO NOT EDIT - Generated by scripts/generate-aligned.mjs
 * Source: schemas/hd_wallet_aligned.fbs
 */

${result.js}

// Export all generated classes and constants
export {
  // Enums
  Curve,
  Error,
  AddressType,
  Network,

  // Size and alignment constants
  BYTES32_SIZE,
  BYTES32_ALIGN,
  BYTES33_SIZE,
  BYTES33_ALIGN,
  BYTES64_SIZE,
  BYTES64_ALIGN,
  EXTENDEDKEYDATA_SIZE,
  EXTENDEDKEYDATA_ALIGN,
  BATCHDERIVEREQUEST_SIZE,
  BATCHDERIVEREQUEST_ALIGN,
  DERIVEDKEYENTRY_SIZE,
  DERIVEDKEYENTRY_ALIGN,
  BATCHSIGNREQUEST_SIZE,
  BATCHSIGNREQUEST_ALIGN,
  HASHENTRY_SIZE,
  HASHENTRY_ALIGN,
  SIGNATUREENTRY_SIZE,
  SIGNATUREENTRY_ALIGN,
  BATCHVERIFYREQUEST_SIZE,
  BATCHVERIFYREQUEST_ALIGN,
  VERIFYENTRY_SIZE,
  VERIFYENTRY_ALIGN,
  VERIFYRESULTENTRY_SIZE,
  VERIFYRESULTENTRY_ALIGN,
  STREAMDERIVECONFIG_SIZE,
  STREAMDERIVECONFIG_ALIGN,
  STREAMSTATUS_SIZE,
  STREAMSTATUS_ALIGN,
  BATCHADDRESSREQUEST_SIZE,
  BATCHADDRESSREQUEST_ALIGN,
  ADDRESSINPUTENTRY_SIZE,
  ADDRESSINPUTENTRY_ALIGN,
  ADDRESSRESULTENTRY_SIZE,
  ADDRESSRESULTENTRY_ALIGN,

  // Offset objects
  Bytes32Offsets,
  Bytes33Offsets,
  Bytes64Offsets,
  ExtendedKeyDataOffsets,
  BatchDeriveRequestOffsets,
  DerivedKeyEntryOffsets,
  BatchSignRequestOffsets,
  HashEntryOffsets,
  SignatureEntryOffsets,
  BatchVerifyRequestOffsets,
  VerifyEntryOffsets,
  VerifyResultEntryOffsets,
  StreamDeriveConfigOffsets,
  StreamStatusOffsets,
  BatchAddressRequestOffsets,
  AddressInputEntryOffsets,
  AddressResultEntryOffsets,

  // View classes
  Bytes32View,
  Bytes32ArrayView,
  Bytes33View,
  Bytes33ArrayView,
  Bytes64View,
  Bytes64ArrayView,
  ExtendedKeyDataView,
  ExtendedKeyDataArrayView,
  BatchDeriveRequestView,
  BatchDeriveRequestArrayView,
  DerivedKeyEntryView,
  DerivedKeyEntryArrayView,
  BatchSignRequestView,
  BatchSignRequestArrayView,
  HashEntryView,
  HashEntryArrayView,
  SignatureEntryView,
  SignatureEntryArrayView,
  BatchVerifyRequestView,
  BatchVerifyRequestArrayView,
  VerifyEntryView,
  VerifyEntryArrayView,
  VerifyResultEntryView,
  VerifyResultEntryArrayView,
  StreamDeriveConfigView,
  StreamDeriveConfigArrayView,
  StreamStatusView,
  StreamStatusArrayView,
  BatchAddressRequestView,
  BatchAddressRequestArrayView,
  AddressInputEntryView,
  AddressInputEntryArrayView,
  AddressResultEntryView,
  AddressResultEntryArrayView,
};
`;
writeFileSync(jsOutputPath, jsContent);

// Print layout information
console.log('\nGenerated struct layouts:');
for (const [name, layout] of Object.entries(result.layouts)) {
  console.log(`  ${name}: ${layout.size} bytes (align ${layout.align})`);
}

console.log('\nCode generation complete!');
